---
- hosts: group1
  tasks:
  - name: installing {{pkg_name}}
    vars:
      pkg_name: httpd
      pkg_state: present
    yum: name = {{pkg_name}} state = {{pkg_state}}
  - name: installing {{pkg_name}}
    vars:
      pkg_name: tomcat
      pkg_state: present
    yum: name = {{pkg_name}} state = {{pkg_state}}
